release:
  mode: replace

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: po-test
    tap:
      owner: sahma19
      name: homebrew-tap
    commit_author:
      name: sahma19
      email: shd@energinet.dk
    folder: Formula
    homepage: "https://github.com/sahma19/po-test"
    description: "CLI to run unit tests against prometheus-operator manifests"
    install: |
      bin.install "po-test"
    license: "LGPL-3.0-or-later"
