version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directories:
      - "*/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
