name: docker

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ++ Export global vars for current job
        id: current-job
        run: |
          if [ ${{github.ref_name}} = "main" ]; then
            echo "::set-output name=VERSION::latest"
          else
            echo "::set-output name=VERSION::${{ github.ref_name }}"
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ghcr.io/loveholidays/po-test:${{ steps.current-job.outputs.VERSION }}